### PR TITLE
Dp sloth

### PR DESCRIPTION
**Pull request by obscure-shadow**
```
git fetch --all
git checkout DP_sloth
```

check out the code. the one test I wrote passes. I have no Idea what I'm doing... please send help. and cookies...

### CODE REVIEW

**Comment by Megraohoh** [comment]
I can't help and I don't have cookies. Also the test failed for me. 

E
======================================================================
ERROR: test_for_sloth_class (__main__.Sloth_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sloth_test.py", line 6, in test_for_sloth_class
    self.assertTrue(Sloth())
  File "/Users/meghandebity/workspace/python/exercises/tdd-zoo/sloth.py", line 15, in __init__
    super().__init__(self)
TypeError: __init__() takes 1 positional argument but 2 were given

----------------------------------------------------------------------
Ran 1 test in 0.023s

FAILED (errors=1)

**Comment by rsbabcock** [comment]
When I ran it the test failed for this reason

```
======================================================================
ERROR: test_for_sloth_class (__main__.Sloth_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sloth_test.py", line 6, in test_for_sloth_class
    self.assertTrue(Sloth())
  File "/Users/rachaelbabcock/Workspaces/groupProjects/tdd-zoo/sloth.py", line 15, in __init__
    super().__init__(self)
TypeError: __init__() takes 1 positional argument but 2 were given

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

I think you may need to instantiate the sloth class before you test it

try 

sloth = Sloth()

then use sloth in the test instead of Sloth()

**Comment by rsbabcock** [comment]
Great! I can make it fail :D 🚢

**Comment by Megraohoh** [comment]
Test passed but it looks like you have some merge conflicts

**Comment by obscure-shadow** [comment]
yeah it kept yelling at me that my __pycache__ file was untracked and that was what was conflicting. added a .gitignore so hopefully that wont happen in the future. @Megraohoh

**Pull request merged**
