### PR TITLE
added animal class and first test

### PR DESCRIPTION
**Pull request by rsbabcock**
Animal Class - 

```
git fetch --all
git check out animalClass
```

run test to make sure that animal.say_something() returns true

### CODE REVIEW

**Comment by CashewRose** [comment]
```
➜  experiment git:(animalClass) ✗ python animal_test.py
set up module
.tear down module

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
``` 
This is what I am getting. Is that ok?

**Comment by MrErin** [comment]
Looks good to me. 🚢

**Comment by rsbabcock** [comment]
@CashewRose yes, so far that's what it's suppose to look like

**Comment by rsbabcock** [comment]
is this good?

**Pull request merged**
