### PR TITLE
Pzc habitat class creation

### PR DESCRIPTION
**Pull request by paulzimmclay**
```
git fetch --all
git checkout pzc-habitat-class-creation
python habitat_test.py
```

### CODE REVIEW

**Comment by rsbabcock** [comment]
I can't get it to fail the test by changing test parameters to [] or None or False

**Comment by Megraohoh** [comment]
Followed the terminal commands. Test passed.

**Comment by paulzimmclay** [comment]
@rsbabcock test was unfailable before, but now can fail. check it out again.

**Comment by jacobxcodes** [comment]
Test works now. Fantastic testing mechanisms @paulzimmclay

**Comment by rsbabcock** [comment]
@paulzimmclay 

FAILURE is great!

🚢

**Pull request merged**
